language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: "Tests"
      name: "Unit tests"
      script: npm test
      after_script:
        - cat ./coverage/lcov.info | coveralls
    - name: "Eslint"
      script: npm run lint
    - stage: "Build"
      name: "Gridsome build"
      script: npm run build
    - stage: "Performance check"
      name: "Lighthouse CI"
      addons:
        chrome: stable
      before_install:
        - npm install -g @lhci/cli
        - npm run build
        - openssl req -batch -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem
      script:
        - lhci autorun
