language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: "Tests"
      name: "Unit tests"
      script: npm test
      after_script:
        - cat ./coverage/lcov.info | coveralls
    - name: "Eslint"
      script: npm run lint
