backend:
  name: github
  repo: Sites-CS/portfolio
  branch: base

media_folder: "static/uploads"
public_folder: "/uploads"

locale: fr

collections:
  - name: "portfolioItems"
    label: "Création"
    folder: "content/portfolio-items"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description", name: "excerpt", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "date"}
      - {label: "Lien du site", name: "link", widget: "string"}
      - {label: "Image de couverture", name: "coverImage", widget: "image", required: false}
  - name: "categories"
    label: "Catégories"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description", name: "excerpt", widget: "string"}
      - {label: "Image de couverture", name: "coverImage", widget: "image"}
  - name: "technologies"
    label: "Technologies"
    folder: "content/technologies"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description", name: "excerpt", widget: "string"}
      - {label: "Image de couverture", name: "coverImage", widget: "image"}
  - name: "blocs"
    label: "Blocs de texte"
    folder: "content/blocks"
    create: true
    id: "{{id}}"
    fields:
      - {label: "Nom", name: "name", widget: "string"}
      - {label: "Contenu", name: "content", widget: "string"}
